Repository 42-jkoers/ft_transcendence, pull requests merged in 2022-06, with the labels that each got.

#75 Load msgs for selected room
  backend/src/chat/message/message.entity.ts
  backend/src/chat/message/message.interface.ts
  backend/src/chat/message/message.service.ts
  backend/src/gateway/chat.gateway.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ChatBox.vue
  frontend/src/types/Message.interface.ts
  frontend/src/views/ChatView.vue
Labels: enhancement

#86 User add friend
  backend/src/gateway/chat.gateway.ts
  backend/src/user/dto/Friend.dto.ts
  backend/src/user/dto/index.ts
  backend/src/user/enum/edit.friend.enum.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.interface.ts
  backend/src/user/user.service.ts
  frontend/src/components/EditFriendButton.vue
  frontend/src/components/FriendList.vue
  frontend/src/components/FriendRequest.vue
  frontend/src/components/HomeMenu.vue
  frontend/src/components/UserProfileCard.vue
  frontend/src/router/index.ts
  frontend/src/types/EditFriendActionType.ts
  frontend/src/views/FriendsView.vue
  note/aileen.txt
Labels: enhancement

#92 Messages are being loaded and rendered in rooms properly
  backend/src/gateway/chat.gateway.ts
  frontend/src/components/ChatBox.vue
Labels: enhancement

#96 Friend notification
  .gitignore
  frontend/src/components/EditFriendButton.vue
  frontend/src/components/FriendActionMessage.vue
  frontend/src/components/FriendList.vue
  frontend/src/components/FriendRequest.vue
  frontend/src/components/UserProfileCard.vue
  frontend/src/types/EditFriendActionType.ts
  frontend/src/types/editFriend.ts
  note/aileen.txt
  upload/.gitkeep
Labels: enhancement

#98 Context menu for user in chat
  frontend/src/components/ChatBox.vue
Labels: enhancement

#107 Toast
  frontend/src/components/ConfirmButton.vue
  frontend/src/components/EditFriendButton.vue
  frontend/src/components/FriendActionMessage.vue
  frontend/src/components/FriendList.vue
  frontend/src/components/FriendRequest.vue
  frontend/src/components/LogOut.vue
  frontend/src/components/UserProfileCard.vue
  frontend/src/components/WebsiteTitle.vue
  frontend/src/types/EditFriendActionType.ts
  frontend/src/types/editFriend.ts
  frontend/src/types/editFriendAction.ts
  frontend/src/types/errorManagement.ts
  frontend/src/views/UserHomeView.vue
  note/aileen.txt
Labels: enhancement

#110 105 left click on userchip in chat should result in a user profile card pop up
  frontend/src/components/ChatBox.vue
  frontend/src/components/ChatBoxUserProfileDialogue.vue
  frontend/src/views/ChatView.vue
Labels: enhancement

#114 Msgs for same user with multiple sockets
  backend/src/chat/channel/channel.module.ts
  backend/src/gateway/chat.gateway.ts
Labels: bug

#127 User online status
  backend/src/auth/auth.service.ts
  backend/src/chat/chat.module.ts
  backend/src/gateway/chat.gateway.ts
  backend/src/user/dto/createUser.dto.ts
  backend/src/user/init.user.service.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.interface.ts
  backend/src/user/user.module.ts
  backend/src/user/user.service.ts
  frontend/src/components/FriendList.vue
  frontend/src/components/FriendRequest.vue
  frontend/src/components/UserProfileCard.vue
  frontend/src/components/UserStatus.vue
  frontend/src/types/UserProfile.interface.ts
  frontend/src/views/FriendsView.vue
  note/aileen.txt
Labels: enhancement

#131 User deregister
  backend/src/gateway/chat.gateway.ts
  backend/src/user/dto/deleteUser.dto.ts
  backend/src/user/dto/index.ts
  backend/src/user/user.controller.ts
  backend/src/user/user.service.ts
  frontend/src/components/UpdateUserInfo.vue
  frontend/src/components/WebsiteTitle.vue
  frontend/src/views/RegisterView.vue
  note/aileen.txt
Labels: enhancement

#142 115 add new users to room
  backend/src/chat/room/room.service.ts
  backend/src/gateway/main.gateway.ts
  backend/src/user/user.entity.ts
  backend/src/user/user.service.ts
  frontend/src/components/ChatBox.vue
  frontend/src/components/ChatBoxAddUsersDialogue.vue
Labels: enhancement

#147 user_context_menu_visiblity
  frontend/src/components/ChatBox.vue
Labels: enhancement

#151 Remove register process
  backend/src/auth/auth.service.ts
  backend/src/auth/oauth/oauth.strategy.ts
  backend/src/user/dto/validateUser.dto.ts
  frontend/src/router/index.ts
  frontend/src/store/index.ts
  frontend/src/views/RegisterView.vue
Labels: improvement

#154 Watch game
  backend/src/game/game.controller.ts
  backend/src/game/game.module.ts
  backend/src/game/game.service.ts
  frontend/src/components/JoinGame.vue
  frontend/src/components/UpdateUserInfo.vue
  frontend/src/components/WatchGame.vue
  frontend/src/store/index.ts
  frontend/src/views/GameView.vue
  note/aileen.txt
Labels: enhancement

#159 Gamelist change to socket
  backend/src/app.module.ts
  backend/src/game/game.controller.ts
  backend/src/game/game.module.ts
  backend/src/gateway/main.gateway.ts
  frontend/src/components/WatchGame.vue
  frontend/src/views/GameView.vue
  note/aileen.txt
Labels: improvement

#161 add import router in store index.ts
  frontend/src/store/index.ts
Labels: bug
